spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: false
      routes:
        - id: shopizer-security-service
          uri: lb://shopizer-security-service
          predicates:
            - Path=/api/v1/sec/**
      loadbalancer:
        use404: false

server:
  port: 20000
  shutdown: GRACEFUL
  ssl:
    enabled: false
    key-store: classpath:keystore/api-gateway.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: api-gateway

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:12345/eureka
    fetch-registry: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
      show-components: always