spring:
  application:
    name: eureka-server

server:
  port: 12345 # Eureka Port
  shutdown: GRACEFUL
  http2:
    enabled: false
  ssl:
    enabled: false
    key-store: classpath:keystore/eureka.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: eureka

# Eureka 客户端连接配置
eureka:
  client:
    service-url:
      # Register self
      defaultZone: http://127.0.0.1:${server.port}/eureka
    # Do not fetch itself
    fetch-registry: false
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    metadataMap:
      prometheus:
        scrape: true
        path: ${management.endpoints.web.basePath:/actuator}/prometheus
        port: ${management.server.port:${server.port}}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
      show-components: always
